@RiverBooks.Web_HostAddress = https://localhost:7179
@BookId=d1fe50d3-a4f7-4976-939a-80c1a714bb61

###
GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json

###
GET {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/books
Content-Type: application/json
Accept: application/json
{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "price": 10.99
}

###
DELETE {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/books/{{BookId}}/pricehistory
Content-Type: application/json
Accept: application/json
{
  "id": "{{BookId}}",
  "newPrice": 12.88
}

###
POST {{RiverBooks.Web_HostAddress}}/users
Content-Type: application/json
Accept: application/json
{
  "email": "test@test.com",
  "password": "SenhaSegura123_"
}

###
POST {{RiverBooks.Web_HostAddress}}/users/login
Content-Type: application/json
Accept: application/json
{
  "email": "test@test.com",
  "password": "SenhaSegura123_"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzQ4NzI5NTg1LCJleHAiOjE3NDg3MzMxODUsIm5iZiI6MTc0ODcyOTU4NX0.VVEql0ISBXv_V3-PWMLwUb4_H9o8Oi_WOXu5nHHNwXc

### Add item to cart
POST {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "bookId": "5bf6c1ac-97ea-4c31-8920-f8849822c340",
  "quantity": 2
}

### 
GET {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{RiverBooks.Web_HostAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###
POST {{RiverBooks.Web_HostAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "shippingAddressId": "a27cfbc8-3195-4fba-abb4-f344764f9e5f",
  "billingAddressId": "a27cfbc8-3195-4fba-abb4-f344764f9e5f"
}

### List Addresses
GET {{RiverBooks.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

### Add Address to User
POST {{RiverBooks.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "street1": "jUUJ Legal",
  "street2": "Number 444",
  "city": "Santiago",
  "state": "RS",
  "postalCode": "123456712",
  "country": "BR"
}

### FLUSH CACHE

POST {{RiverBooks.Web_HostAddress}}/flushcache
Accept: application/json
Content-Type: application/json

{
}